kind: Pod
apiVersion: v1
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl-pod
      image: radial/busyboxplus:curl
      command: ["/bin/bash"]
      args: ["-c", "while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: OnFailure